# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Dict, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from edgeimpulse_api.models.ai_actions_data_category import AIActionsDataCategory
from edgeimpulse_api.models.get_ai_actions_config_response_all_of_last_preview_job import GetAIActionsConfigResponseAllOfLastPreviewJob

class GetAIActionsConfigResponseAllOf(BaseModel):
    data_preview_category: AIActionsDataCategory = Field(..., alias="dataPreviewCategory")
    data_without_metadata_key: Optional[StrictStr] = Field(None, alias="dataWithoutMetadataKey")
    max_data_preview_count: StrictInt = Field(..., alias="maxDataPreviewCount")
    last_used_transformation_block_id: Optional[StrictInt] = Field(None, alias="lastUsedTransformationBlockId")
    last_used_parameters: Optional[Dict[str, StrictStr]] = Field(None, alias="lastUsedParameters")
    grid_column_count: StrictInt = Field(..., alias="gridColumnCount")
    last_preview_job: Optional[GetAIActionsConfigResponseAllOfLastPreviewJob] = Field(None, alias="lastPreviewJob")
    __properties = ["dataPreviewCategory", "dataWithoutMetadataKey", "maxDataPreviewCount", "lastUsedTransformationBlockId", "lastUsedParameters", "gridColumnCount", "lastPreviewJob"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = False

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetAIActionsConfigResponseAllOf:
        """Create an instance of GetAIActionsConfigResponseAllOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of last_preview_job
        if self.last_preview_job:
            _dict['lastPreviewJob'] = self.last_preview_job.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetAIActionsConfigResponseAllOf:
        """Create an instance of GetAIActionsConfigResponseAllOf from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return GetAIActionsConfigResponseAllOf.construct(**obj)

        _obj = GetAIActionsConfigResponseAllOf.construct(**{
            "data_preview_category": obj.get("dataPreviewCategory"),
            "data_without_metadata_key": obj.get("dataWithoutMetadataKey"),
            "max_data_preview_count": obj.get("maxDataPreviewCount"),
            "last_used_transformation_block_id": obj.get("lastUsedTransformationBlockId"),
            "last_used_parameters": obj.get("lastUsedParameters"),
            "grid_column_count": obj.get("gridColumnCount"),
            "last_preview_job": GetAIActionsConfigResponseAllOfLastPreviewJob.from_dict(obj.get("lastPreviewJob")) if obj.get("lastPreviewJob") is not None else None
        })
        return _obj

